# Generated by Django 5.2 on 2025-05-12 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
        ('participants', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('duree', models.IntegerField(help_text='Durée en minutes')),
                ('date_debut', models.DateTimeField()),
                ('capacite_max', models.IntegerField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('niveau_difficulte', models.CharField(blank=True, max_length=20, null=True)),
                ('age_minimum', models.IntegerField(blank=True, null=True)),
                ('age_maximum', models.IntegerField(blank=True, null=True)),
                ('annulee', models.BooleanField(default=False)),
                ('raison_annulation', models.TextField(blank=True, null=True)),
                ('points_cles', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('infrastructure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='infrastructure.infrastructure')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='staff.responsable')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'db_table': 'activite',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ActiviteAnimateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animateurs_relation', to='activities.activite')),
                ('animateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_relation', to='staff.animateur')),
            ],
            options={
                'db_table': 'activite_animateur',
                'unique_together': {('activite', 'animateur')},
            },
        ),
        migrations.CreateModel(
            name='ActiviteMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantite_requise', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels_relation', to='activities.activite')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_relation', to='infrastructure.materiel')),
            ],
            options={
                'db_table': 'activite_materiel',
                'unique_together': {('activite', 'materiel')},
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('en_attente', 'En attente'), ('annule', 'Annulé')], default='inscrit', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('a_participe', models.BooleanField(default=False)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='activities.activite')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='participants.participant')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'db_table': 'inscription',
                'unique_together': {('participant', 'activite')},
            },
        ),
    ]
