# Generated by Django 5.2 on 2025-05-12 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('health_notes', models.TextField(blank=True, null=True)),
                ('has_authorization', models.BooleanField(default=False, help_text="Parent's authorization to participate")),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'db_table': 'participant',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='participant_files/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('file_type', models.CharField(choices=[('medical', 'Medical Document'), ('authorization', 'Authorization Form'), ('id', 'Identity Document'), ('other', 'Other Document')], default='other', max_length=20)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='participants.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
