# Generated by Django 5.2 on 2025-05-12 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('capacite', models.IntegerField(blank=True, null=True)),
                ('localisation', models.CharField(blank=True, max_length=100, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('maintenance_notes', models.TextField(blank=True, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Infrastructure',
                'verbose_name_plural': 'Infrastructures',
                'db_table': 'infrastructure',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantite_disponible', models.IntegerField(default=0)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fournisseur', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériels',
                'db_table': 'materiel',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='InfrastructureReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('motif', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='infrastructure.infrastructure')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
